require('dotenv').config();

const axios = require('axios');
const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

if (!process.env.BIOMETRIC_SECRET_KEY && !process.env.SECURITY_KEY) {
  console.error(
    'BIOMETRIC_SECRET_KEY or SECURITY_KEY is required. Use the same value in the seed script and backend server.'
  );
  process.exit(1);
}

const { encryptBiometric } = require('../utils/crypto.util');
const { signTempToken } = require('../services/token.service');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/mfa_biometric';
const API_CONTAINER_URL = process.env.API_CONTAINER_URL || 'http://127.0.0.1:9001';
const BACKEND_STEP_UP_URL = process.env.BACKEND_STEP_UP_URL || 'http://127.0.0.1:4000/api/auth/step-up';
const PRIVATE_LSTM_SERVICE_URL = process.env.PRIVATE_LSTM_SERVICE_URL || process.env.CLOUD_SERVICE_URL || 'http://127.0.0.1:8000';
const ML_USERNAME = process.env.ML_SERVICE_USERNAME || 'bmfa_user';
const ML_PASSWORD = process.env.ML_SERVICE_PASSWORD || 'your_secure_password_here';

const TENANT_KEY = process.env.SEED_TENANT_KEY || 'acme-demo';
const USER_EMAIL = process.env.SEED_USER_EMAIL || 'demo.biometric@acme.test';
const USER_NAME = process.env.SEED_USER_NAME || 'Demo Biometric User';

const args = new Set(process.argv.slice(2));
const shouldCallStepUp = args.has('--call-step-up');
const shouldCallBackendDirectly = args.has('--direct-backend');

const Tenant = mongoose.model('SeedTenant', new mongoose.Schema({}, {
  collection: 'tenants',
  strict: false,
  versionKey: false
}));

const User = mongoose.model('SeedUser', new mongoose.Schema({}, {
  collection: 'users',
  strict: false,
  versionKey: false
}));

const BiometricProfile = mongoose.model('SeedBiometricProfile', new mongoose.Schema({}, {
  collection: 'biometricprofile',
  strict: false,
  versionKey: false
}));

function createOrganicSignature({ points = 180, offsetX = 0, offsetY = 0, jitter = 0 }) {
  const strokePoints = [];
  for (let i = 0; i < points; i += 1) {
    const t = i * 12;
    const angle = i / 14;
    const wave = Math.sin(angle) * 24;
    const curve = Math.cos(angle / 2) * 12;
    strokePoints.push({
      x: 90 + i * 1.7 + wave + offsetX + Math.sin(i) * jitter,
      y: 180 + curve + Math.sin(i / 7) * 36 + offsetY + Math.cos(i) * jitter,
      t,
      p: 0.5
    });
  }

  return {
    timestamp: new Date().toISOString(),
    stroke_points: strokePoints,
    stroke_duration_ms: strokePoints.at(-1).t
  };
}

function padSignature(signature, target = 1200) {
  const points = signature.stroke_points.slice();
  const realLength = points.length;
  const last = points.at(-1);

  while (points.length < target) {
    points.push({
      x: last.x,
      y: last.y,
      t: last.t + (points.length - realLength + 1),
      p: last.p
    });
  }

  return {
    normalized_stroke: points.slice(0, target),
    real_length: realLength,
    features: {
      num_points: target,
      real_length: realLength,
      total_distance: 0,
      velocity_mean: 0,
      velocity_max: 0,
      duration_ms: signature.stroke_duration_ms
    }
  };
}

function fallbackMasterFeature() {
  const mean = Array.from({ length: 400 }, () => [0, 0, 0, 0]);
  const std = Array.from({ length: 400 }, () => [0.01, 0.01, 0.01, 0.01]);
  return { mean, std };
}

async function buildMasterFeature(signatures) {
  const normalized = signatures.map((signature) => padSignature(signature));
  const token = Buffer.from(`${ML_USERNAME}:${ML_PASSWORD}`, 'utf8').toString('base64');

  try {
    const response = await axios.post(
      `${PRIVATE_LSTM_SERVICE_URL}/api/biometric/enroll`,
      { signatures: normalized },
      {
        headers: {
          Authorization: `Basic ${token}`,
          'Content-Type': 'application/json'
        },
        timeout: 15000,
        proxy: false
      }
    );

    if (response.data?.master_feature?.mean) {
      console.log(`[seed] Master feature generated by private LSTM service: ${PRIVATE_LSTM_SERVICE_URL}`);
      return response.data.master_feature;
    }
  } catch (error) {
    console.warn(`[seed] Private LSTM enrollment unavailable, using deterministic fallback master feature: ${error.message}`);
  }

  return fallbackMasterFeature();
}

async function seedTenantUserAndBiometric() {
  await mongoose.connect(MONGO_URI);

  const now = new Date();
  const tenant = await Tenant.findOneAndUpdate(
    { tenantKey: TENANT_KEY },
    {
      $set: {
        tenantKey: TENANT_KEY,
        companyName: 'ACME Demo Organization',
        domain: 'acme.test',
        status: 'Active',
        tier: 'demo',
        tokenSettings: {
          arcTokenExpirySeconds: 300,
          issuerName: `https://arc-auth.service/${TENANT_KEY}`,
          algorithm: 'RS256'
        },
        updatedAt: now
      },
      $setOnInsert: { createdAt: now }
    },
    { upsert: true, returnDocument: 'after' }
  );

  const user = await User.findOneAndUpdate(
    { email: USER_EMAIL },
    {
      $set: {
        googleId: `seed-google-${USER_EMAIL}`,
        email: USER_EMAIL,
        name: USER_NAME,
        role: 'user',
        status: 'Active',
        active: true,
        isActive: true,
        tenantId: tenant._id,
        tenantKey: TENANT_KEY,
        tenant: {
          _id: tenant._id,
          key: TENANT_KEY
        },
        updatedAt: now
      },
      $setOnInsert: { createdAt: now }
    },
    { upsert: true, returnDocument: 'after' }
  );

  const enrollmentSignatures = [
    createOrganicSignature({ offsetX: 0, offsetY: 0, jitter: 0.1 }),
    createOrganicSignature({ offsetX: 1.5, offsetY: -1, jitter: 0.2 }),
    createOrganicSignature({ offsetX: -1, offsetY: 1.2, jitter: 0.15 }),
    createOrganicSignature({ offsetX: 0.8, offsetY: 0.7, jitter: 0.12 }),
    createOrganicSignature({ offsetX: -0.5, offsetY: -0.4, jitter: 0.18 })
  ];

  const masterFeature = await buildMasterFeature(enrollmentSignatures);
  const encrypted = encryptBiometric(masterFeature);

  const profile = await BiometricProfile.findOneAndUpdate(
    { userId: user._id.toString(), tenantId: tenant._id },
    {
      $set: {
        userId: user._id.toString(),
        tenantId: tenant._id,
        tenantKey: TENANT_KEY,
        masterFeatureEncrypted: encrypted.encryptedData,
        iv: encrypted.iv,
        authTag: encrypted.authTag,
        samplesUsed: enrollmentSignatures.length,
        modelVersion: 'lstm_mini_v1',
        lastUpdated: now,
        updatedAt: now
      },
      $setOnInsert: { createdAt: now }
    },
    { upsert: true, returnDocument: 'after' }
  );

  await User.updateOne(
    { _id: user._id },
    {
      $set: {
        biometricTemplate: {
          biometricProfileId: profile._id,
          modelVersion: 'lstm_mini_v1',
          samplesUsed: enrollmentSignatures.length,
          enrolledAt: now
        }
      }
    }
  );

  const token = signTempToken({
    sub: user._id.toString(),
    email: USER_EMAIL,
    role: 'user',
    tenantId: tenant._id.toString(),
    tenantKey: TENANT_KEY,
    login_id: `seed_login_${uuidv4()}`,
    nonce: uuidv4()
  });

  return {
    tenant,
    user,
    profile,
    token,
    loginSignature: createOrganicSignature({ offsetX: 0.4, offsetY: -0.3, jitter: 0.1 })
  };
}

async function callStepUp({ token, loginSignature }) {
  if (shouldCallBackendDirectly) {
    const normalizedSignature = padSignature(loginSignature);
    const response = await axios.post(
      BACKEND_STEP_UP_URL,
      {
        tenantKey: TENANT_KEY,
        normalized_signature: normalizedSignature
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        timeout: 30000,
        proxy: false
      }
    );
    return response.data;
  }

  const response = await axios.post(
    `${API_CONTAINER_URL}/auth/step-up`,
    loginSignature,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-Tenant-Key': TENANT_KEY
      },
      timeout: 30000,
      proxy: false
    }
  );
  return response.data;
}

async function main() {
  try {
    const seeded = await seedTenantUserAndBiometric();

    console.log('\n[seed] Ready user for biometric login');
    console.log(`  tenantKey: ${TENANT_KEY}`);
    console.log(`  tenantId: ${seeded.tenant._id}`);
    console.log(`  userId: ${seeded.user._id}`);
    console.log(`  email: ${USER_EMAIL}`);
    console.log(`  biometricProfileId: ${seeded.profile._id}`);
    console.log('\n[seed] ARC 0.5 token for manual tests:');
    console.log(seeded.token);

    if (shouldCallStepUp) {
      console.log(
        shouldCallBackendDirectly
          ? `\n[test] Calling backend directly: ${BACKEND_STEP_UP_URL}`
          : `\n[test] Calling API Container: ${API_CONTAINER_URL}/auth/step-up`
      );
      const result = await callStepUp(seeded);
      console.log('[test] Step-up response:');
      console.log(JSON.stringify(result, null, 2));
    } else {
      console.log('\n[seed] To run the full step-up call, start backend + apiContainer + private LSTM and rerun:');
      console.log('  npm run seed:test-login -- --call-step-up');
      console.log('\n[seed] To test only the backend orchestrator, start backend + private LSTM and rerun:');
      console.log('  npm run seed:test-login -- --call-step-up --direct-backend');
    }
  } finally {
    await mongoose.disconnect();
  }
}

main().catch(async (error) => {
  const status = error.response?.status;
  const data = error.response?.data;
  console.error('[seed] Failed:', status ? `${status} ${JSON.stringify(data)}` : error.message);
  await mongoose.disconnect().catch(() => {});
  process.exit(1);
});
