"""
Inference-only model loader using TFLite runtime.
The production artifact is a .tflite file generated by export_tflite.py.
No Keras / training dependencies are imported here.
"""
import os
import logging
import numpy as np

logger = logging.getLogger(__name__)

try:
    import tflite_runtime.interpreter as tflite
    _Interpreter = tflite.Interpreter
except ImportError:
    try:
        from tensorflow import lite as _tf_lite
        _Interpreter = _tf_lite.Interpreter
    except ImportError:
        _Interpreter = None


def load_ml_model():
    """
    Load the TFLite model from the path set in MODEL_PATH.
    Returns the interpreter object or None if unavailable.
    """
    from .config import settings

    if _Interpreter is None:
        logger.error(
            "Neither tflite_runtime nor tensorflow.lite is installed. "
            "Install tflite-runtime: pip install tflite-runtime"
        )
        return None

    model_path = settings.model_path

    if not os.path.exists(model_path):
        logger.warning(
            f"TFLite model not found at '{model_path}'. "
            "Run export_tflite.py to generate it and update MODEL_PATH in .env."
        )
        return None

    if not model_path.endswith(".tflite"):
        logger.error(
            f"MODEL_PATH points to '{model_path}' which is not a .tflite file. "
            "Run export_tflite.py to convert and update MODEL_PATH."
        )
        return None

    try:
        interpreter = _Interpreter(model_path=model_path)
        interpreter.allocate_tensors()
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()
        logger.info(
            f"✅ TFLite model loaded from '{model_path}' | "
            f"input={input_details[0]['shape']} dtype={input_details[0]['dtype'].__name__} | "
            f"output={output_details[0]['shape']}"
        )
        return interpreter
    except Exception as e:
        logger.error(f"❌ Failed to load TFLite model: {e}")
        return None


def compute_embedding(interpreter, preprocessed_signature_tensor):
    """
    Run inference with the TFLite interpreter.

    Args:
        interpreter: Loaded TFLite Interpreter from load_ml_model().
        preprocessed_signature_tensor: np.ndarray of shape (400, N_FEATURES) or (1, 400, N_FEATURES).

    Returns:
        np.ndarray: Flat embedding vector (e.g. shape (128,)).
    """
    if interpreter is None:
        raise ValueError("TFLite interpreter is not loaded.")

    tensor = np.asarray(preprocessed_signature_tensor, dtype=np.float32)
    if tensor.ndim == 2:
        tensor = np.expand_dims(tensor, axis=0)  # -> (1, 400, N_FEATURES)

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    interpreter.set_tensor(input_details[0]["index"], tensor)
    interpreter.invoke()
    embedding = interpreter.get_tensor(output_details[0]["index"])

    return embedding[0]  # (embedding_dim,)